version: "3.9"

services:
  mssql-custom:
    build: .
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1_
      - MSSQL_PID=Developer
      # - MSSQL_DATA_DIR=/my/file/path
    # volumes: 
      # - /Users/mo/code/hasql-on-docker/6-docker-mssql/data:/var/opt/mssql/data
      # - /Users/mo/code/hasql-on-docker/6-docker-mssql/secrets:/var/opt/mssql/secrets 

# TODO: 
# - Volume Share
# - Auto