apiVersion: v1
kind: Pod
metadata:
  name: dbs
  labels:
    run: dbs
spec:
  containers:
    - name: dbs
      image: mokari94/dbservice
      imagePullPolicy: Always # IfNotPresent
      env:
        - name: LICENSE_KEY
          value: SCOTLAND
      ports: 
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: /user/1
          port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dbs
  labels:
    run: dbs
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    run: dbs
  type: LoadBalancer
